In [160]:
import numpy as np

In [2]:
a = np.arange(10)

In [4]:
a.itemsize #traz quantidade de bytes

4

In [6]:
a.size #Traz quantidade de elementos

10

In [10]:
a.nbytes # Traz o total de bytes do array

40

# Criação automática de arrays

In [16]:
a.shape = (5, 2)

In [17]:
np.full(5, 20) #Cria um array do tamanho especificado com apenas o elemento especificado 

array([20, 20, 20, 20, 20])

In [20]:
np.full_like(a, a.mean(), dtype='float32')

array([[4.5, 4.5],
       [4.5, 4.5],
       [4.5, 4.5],
       [4.5, 4.5],
       [4.5, 4.5]], dtype=float32)

In [22]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.diag([5, 10, 5, 2])

array([[ 5,  0,  0,  0],
       [ 0, 10,  0,  0],
       [ 0,  0,  5,  0],
       [ 0,  0,  0,  2]])

In [30]:
np.repeat(a, 2)

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9])

In [40]:
repetida = np.repeat(np.array([[1, 2, 3]]), 3, axis=0) #axis = 0 -> linhas
                                                       #axis = 1 -> colunas

In [43]:
repetida.T #Inverte linha por coluna

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [45]:
np.average(a) #Análogo a .mean()

4.5

In [47]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [50]:
a.sum(axis=1)

array([ 1,  5,  9, 13, 17])

### Carregando dados TXT em numpy

In [54]:
arquivo = np.genfromtxt('data.txt', delimiter=',')

In [55]:
arquivo.shape

(3, 18)

### Máscara

In [62]:
matriz = np.random.randint(1, 100, (5, 5))

In [63]:
matriz

array([[64, 41, 96, 42, 40],
       [46, 66, 70, 98, 35],
       [60, 56,  5,  9,  8],
       [63, 67, 38, 58, 69],
       [92, 89, 36, 30, 69]])

In [64]:
matriz[matriz>=80]

array([96, 98, 92, 89])

- AND: &
- OR: |

In [65]:
matriz[(matriz < 20) | (matriz > 80)]

array([96, 98,  5,  9,  8, 92, 89])

In [69]:
np.all(matriz > 50)

False

In [70]:
np.any(matriz > 50)

True

# Pandas

In [73]:
import pandas as pd

In [74]:
pd.__version__

'1.1.3'

In [76]:
series = pd.Series([1, 2, 3, 4, 5])

In [79]:
steps = np.Series([1245, 3214, 5124, 2000, 3000], index=['Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta'])

In [80]:
steps

Segunda    1245
Terça      3214
Quarta     5124
Quinta     2000
Sexta      3000
dtype: int64

In [84]:
array = np.array([1245, 3214, 5124, 2000, 3000])
pd.Series(array)

0    1245
1    3214
2    5124
3    2000
4    3000
dtype: int32

In [85]:
pd.Series({'A':1, 'B':2})

A    1
B    2
dtype: int64

In [87]:
steps.index

Index(['Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta'], dtype='object')

In [89]:
steps.values

array([1245, 3214, 5124, 2000, 3000], dtype=int64)

In [90]:
steps.head()

Segunda    1245
Terça      3214
Quarta     5124
Quinta     2000
Sexta      3000
dtype: int64

In [93]:
steps.describe() #Mostra algumas informações da Series

count       5.00000
mean     2916.60000
std      1466.49405
min      1245.00000
25%      2000.00000
50%      3000.00000
75%      3214.00000
max      5124.00000
dtype: float64

In [95]:
steps.min()

1245

In [96]:
steps.max()

5124

In [97]:
steps.mean()

2916.6

In [98]:
steps.std() #Desvio Padrão

1466.494050448211

In [101]:
steps.var() #Variância

2150604.8000000003

In [102]:
steps ** 2

Segunda     1550025
Terça      10329796
Quarta     26255376
Quinta      4000000
Sexta       9000000
dtype: int64

In [104]:
np.sqrt(steps)

Segunda    35.284558
Terça      56.692151
Quarta     71.582121
Quinta     44.721360
Sexta      54.772256
dtype: float64

### Indexação e slice

In [113]:
series[:3]

0    1
1    2
2    3
dtype: int64

In [117]:
steps['Segunda']

1245

In [120]:
steps[0]

1245

In [122]:
steps['Segunda':'Sexta']

Segunda    1245
Terça      3214
Quarta     5124
Quinta     2000
Sexta      3000
dtype: int64

In [125]:
steps['Sexta':'Segunda':-1]

Sexta      3000
Quinta     2000
Quarta     5124
Terça      3214
Segunda    1245
dtype: int64

In [127]:
steps[steps>5000]

Quarta    5124
dtype: int64

In [132]:
steps.isin(steps > 4000)

Segunda    False
Terça      False
Quarta     False
Quinta     False
Sexta      False
dtype: bool

### Exercícios

In [134]:
linguagens = pd.Series({'C': 16.48, 'Java':12.53, 'Python':12.21, 'C++':6.91, 'C#':4.20,
                        'Visual Basic':3.92, 'JavaScript':2.35, 'PHP':2.12, 'R':1.60, 'SQL':1.53})

In [140]:
linguagens.head()
linguagens[5:]

Visual Basic    3.92
JavaScript      2.35
PHP             2.12
R               1.60
SQL             1.53
dtype: float64

In [146]:
fibonacci = [0, 1]
for i in range(9):
    fibonacci.append(fibonacci[i] + fibonacci[i+1])

In [147]:
series = pd.Series(fibonacci, index='a b c d e f g h i j k'.split())

In [150]:
series[(series > 10) & (series < 50)]

h    13
i    21
j    34
dtype: int64

In [154]:
series2 = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 5, 3])

In [157]:
def infos(series):
    print(f'Média: {series.mean()}')
    print(f'Desvio Padrão: {series.std()}')

In [159]:
infos(series2)

Média: 4.818181818181818
Desvio Padrão: 2.522624895547565


In [161]:
arr = np.random.randint(1, 5, 20)

serie = pd.Series(arr)

In [166]:
from collections import Counter

In [171]:
frequencia = Counter(serie)

percentual = {}

for i, v in frequencia.items():
    f = v / len(serie) * 100
    percentual[i] = f

In [174]:
percentual

{2: 20.0, 4: 35.0, 1: 30.0, 3: 15.0}

In [183]:
maior = max(frequencia)

for indice, valor in enumerate(serie):
    if valor != maior:
        serie[indice] = 'Outro valor'

In [184]:
serie

0     Outro valor
1               4
2     Outro valor
3               4
4     Outro valor
5     Outro valor
6               4
7               4
8     Outro valor
9     Outro valor
10              4
11              4
12    Outro valor
13    Outro valor
14    Outro valor
15    Outro valor
16              4
17    Outro valor
18    Outro valor
19    Outro valor
dtype: object

In [232]:
indices = np.arange(10, dtype='int64')

In [233]:
def fatorial(n):
    if n == 1 or n == 0:
        return 1
    return n * fatorial(n-1)

In [234]:
fatoriais = {}
for i in indices:
    n = fatorial(i)
    fatoriais[i] = n
    
series = pd.Series(fatoriais)

In [236]:
series

0         1
1         1
2         2
3         6
4        24
5       120
6       720
7      5040
8     40320
9    362880
dtype: int64